apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: Monitor
spec:
 selector:
   matchLabels:
     app: Monitor
 template:
   metadata:
     labels:
       app: Monitor
   spec:
     nodeSelector:
       moringa: ssd
     containers:
     - name: main
       image: figent/Monitor
